[package]
name = "pi_graph"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4"
pi_hash = "0.1"
pi_share = "0.1"
pi_map = "0.1"
pi_idtree = "0.1"
env_logger = "0.9"

[dev-dependencies]
pcg_rand = "0.13"
rand_core = "0.6"
